### ISSUE TITLE
[FIX] Port limit

### ISSUE THREAD

**Issue by sudo-ramonkey** [Gadielo03/CRC-Py#9]
The port input in client.py doesn't support the port specification:
["For TCP and UDP, a port number is a 16-bit unsigned integer, thus ranging from 0 to 65535."](https://en.wikipedia.org/wiki/Port_(computer_networking))
![Screenshot_20240507_170023](https://github.com/Gadielo03/CRC-Py/assets/71893589/87ad67d1-a10a-44b1-add0-cc087f7900ff)
Please fix :)

**Comment by sudo-ramonkey** [comment]
@Gadielo03

**Comment by Gadielo03** [comment]
Kinda fix
